final.exe:main.o big2.o fact.o
        gcc main.o big2.o fact.o -o final

main.o:main.c
        gcc -c main.c
fact.o:fact.c
        gcc -c fact.c
big2.o:big2.c
        gcc -c big2.c

clean:
        rm -rf *.o final
